# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160716122224 on 2016-08-10 19:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20160810_1851'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AntennaRootCause',
            new_name='AntennaRootCaused',
        ),
        migrations.AlterField(
            model_name='ninjausers',
            name='row_create_ts',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 10, 19, 35, 46, 794359)),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='antenna_cm_error',
            field=models.IntegerField(db_column=b'antenna_cm_error', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='antenna_insuff_qam_error',
            field=models.IntegerField(db_column=b'antenna_insuff_qam_error', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='antenna_network_error',
            field=models.IntegerField(db_column=b'antenna_network_error', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='antenna_qam_error',
            field=models.IntegerField(db_column=b'antenna_qam_error', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='antenna_root_cause',
            field=models.IntegerField(db_column=b'antenna_root_cause', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='antenna_tune_error',
            field=models.IntegerField(db_column=b'antenna_tune_error', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='hardened_check',
            field=models.CharField(db_column=b'hardened_check', default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='mitigate_check',
            field=models.CharField(db_column=b'mitigate_check', default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='row_create_ts',
            field=models.DateTimeField(default=b'2016-08-10T19:35:46.797310+00:00'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='row_update_ts',
            field=models.DateTimeField(default=b'2016-08-10T19:35:46.797346+00:00'),
        ),
    ]
