# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160716122224 on 2016-08-10 19:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_auto_20160810_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antennarootcaused',
            name='antenna_root_caused',
            field=models.CharField(db_column=b'antenna_root_caused', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ninjausers',
            name='row_create_ts',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 10, 19, 40, 6, 747639)),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='row_create_ts',
            field=models.DateTimeField(default=b'2016-08-10T19:40:06.750417+00:00'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='row_update_ts',
            field=models.DateTimeField(default=b'2016-08-10T19:40:06.750452+00:00'),
        ),
    ]
