# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160716122224 on 2016-08-10 20:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_auto_20160810_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninjausers',
            name='admin',
            field=models.CharField(default=b'N', max_length=1),
        ),
        migrations.AlterField(
            model_name='ninjausers',
            name='row_create_ts',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 10, 20, 44, 50, 878394)),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='row_create_ts',
            field=models.DateTimeField(default=b'2016-08-10T20:44:50.881118+00:00'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='row_update_ts',
            field=models.DateTimeField(default=b'2016-08-10T20:44:50.881153+00:00'),
        ),
    ]
